#!/bin/sh
#

initrd=${1:-initrd.img}
ramdisk=${2:-RAMDISK}

if [ ! -f $initrd ]; then
    echo "$initrd does not exist."
    exit 1
fi

if [ -d $ramdisk ]; then
    rm $ramdisk -rf
fi

mkdir -p $ramdisk

zcat $initrd | ( cd $ramdisk; cpio -i )

