#!/bin/sh
#

old_pwd=`pwd`
basepath=`cd $(dirname $0); pwd`
cd $old_pwd
LZ4=$basepath/lz4

if [ "$1" = "-f" ]; then
    forcewrite=yes
    shift
fi

initrd=${1:-initrd.img}
ramdisk=${2:-RAMDISK}

if [ ! -d $ramdisk ]; then
    echo "$ramdisk does not exist."
    exit 1
fi

if [ -f $initrd -a -z "$forcewrite" ]; then
    echo "$initrd already exist."
    exit 1
fi

( cd $ramdisk; find | sort | cpio --quiet -H newc -o ) | $LZ4
mv stdin.lz4  $initrd

